name: "laravel"

services:
  php:
    container_name: "php"
    hostname: "php"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./usuarios:/var/www
    depends_on:
      - mysql
    networks:
      - api_network

  mysql:
    container_name: "mysql"
    hostname: "mysql"
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '33060:3306'
    environment:
      MYSQL_DATABASE: crud_users
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - api_network

  nginx:
    container_name: "nginx"
    hostname: "nginx"
    image: nginx:alpine
    ports:
      - "8500:80"
    restart: always
    volumes:
      - ./usuarios:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - api_network

networks:
  api_network:
    driver: bridge

volumes:
  mysql_data: